default: &default
  client_id: '971181149334-d9avbf8shp6ku8vgpvlkbntcohonhh5s.apps.googleusercontent.com'
  client_secret: '5UgDl6FSacW1DYobM11yPhJt'

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default