# default: &default
#   client_id: '971181149334-d9avbf8shp6ku8vgpvlkbntcohonhh5s.apps.googleusercontent.com'
#   client_secret: '5UgDl6FSacW1DYobM11yPhJt'

development:
  client_id: '971181149334-d9avbf8shp6ku8vgpvlkbntcohonhh5s.apps.googleusercontent.com'
  client_secret: '5UgDl6FSacW1DYobM11yPhJt'

test:
  client_id: '971181149334-d9avbf8shp6ku8vgpvlkbntcohonhh5s.apps.googleusercontent.com'
  client_secret: '5UgDl6FSacW1DYobM11yPhJt'

production:
  client_id: '971181149334-d9avbf8shp6ku8vgpvlkbntcohonhh5s.apps.googleusercontent.com'
  client_secret: '5UgDl6FSacW1DYobM11yPhJt'